chore(client): get unique discovery file and update urls
lumapps/lumapps-sdk pull request #200
Opened 2024-10-02 14:15 UTC by chloecarton

in order to be less restrictive on the url to get the discovery file content, we get the same file independently from the base_url and update the file content with the baseUrl on load.

2024-10-22 08:58 UTC, beroussel requested changes
Otherwise :ok_hand:

2024-10-22 08:58 UTC, beroussel commented on lumapps/api/base_client.py
> +                netloc=self.base_url
If I trust the docs and error messages
```python
if not api_info or "base_url" not in api_info:
            raise BaseClientError(
                "Missing api_info in BaseClient. Use BaseClient"
                '(api_info={"base_url": "https://XX-cell-YYY.api.lumapps.com", ...})'
            )
```
and given that
```python
In [7]: urlparse('https://go-cell-001.api.lumapps.com/_ah/lumsites')._replace(netloc='https://master.ms-cell-001.dev.api.lumapps.com/_ah/lumsites').geturl()
Out[7]: 'https://https://master.ms-cell-001.dev.api.lumapps.com/_ah/lumsites/_ah/lumsites'
```
that can't work

2024-10-23 16:46 UTC, beroussel approved these changes

2024-10-24 13:21 UTC, jssevestre approved these changes

2024-10-24 13:22 UTC, merged